name: generics
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.26.0
  dart_web_audio: ^0.1.2
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
